# Generated by Django 4.2 on 2023-04-20 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('imagen', models.CharField(max_length=255)),
                ('nombre', models.CharField(max_length=255)),
                ('distribuidor', models.CharField(max_length=255)),
                ('ASIN', models.CharField(max_length=255)),
                ('precio', models.FloatField()),
                ('EAN', models.CharField(max_length=255)),
            ],
        ),
    ]
