# Generated by Django 4.2 on 2023-04-21 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amazon_products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='ASIN',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='EAN',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
